### ISSUE TITLE
ImportError: No module named models.CocoPoseNet

### ISSUE THREAD

**Issue by dhgokul** [DeNA/Chainer_Realtime_Multi-Person_Pose_Estimation#27]
**Training process :**
I tried to run the below python script and got import error
**Script :** 
 python gen_ignore_mask.py
**Issue :** 
Traceback (most recent call last):
  File "gen_ignore_mask.py", line 9, in <module>
    from entity import params
  File "/home/gg/Chainer_Realtime_Multi-Person_Pose_Estimation-master/entity.py", line 3, in <module>
    from models.CocoPoseNet import CocoPoseNet
ImportError: No module named models.CocoPoseNet

Model folder files  - PFA "Coco.png"
![coco](https://user-images.githubusercontent.com/5689804/35918340-6cc4ccc0-0c37-11e8-8426-b3b89001a356.png)
Please help me to sort out this issue
Thanks

**Comment by benhunt12** [comment]
Had the same problem. Just copy 'CocoPoseNet.py', 'FaceNet.py' and 'HandNet.py' from the models directory into the directory where you are running 'gen_ignore_mask.py'. Then edit 'entity.py' by removing 'models.' from the beginning of the import lines.

**Comment by dhgokul** [comment]
Thanks !, But we run script in python 2.7 , after upgrade to python 3.5 , it's working

**Comment by dhgokul** [comment]
Closed
